### ISSUE TITLE
Add glossary

### ISSUE THREAD

**Issue by Philipp-Otter** [plan4better/goat#2045]
Sections in the glossary could be:

- [x] H3 gird (our hexagonal grid)
sources: https://h3geo.org/, https://github.com/uber/h3, also videos by uber on youtube etc.
- [x] quintile classification 
sources: We put all values outside of our analysis e.g. travel time greater than our max travel time in the lowest category and all the other values are quintile classified.
![image](https://user-images.githubusercontent.com/91256148/226335906-c8f9fee3-0597-41c6-90d3-d1ea8846c15f.png)
- [x] Accessibility 
- [x] Local accessibility 
- [x] Regional accessibility 
- [x] Connectivity 
- [x] Heatmap

**Comment by iremkapucuoglu** [comment]
I made some changes according to your comments. Can you please check again?

**Comment by UJehle** [comment]
Hi @iremkapucuoglu,
I just checked it and like it. Just left some last minor comments. 
From my point of view, you can already insert it into Github (development branch). Then we can give it a final check, translate it into German and release it. If in the future, further words are coming into our mind, then we can add them at any time.

**Comment by UJehle** [comment]
- [ ] add it to GitHub (@iremkapucuoglu)
- [ ] final check (@UJehle & @EPajares ) 
- [ ] translation to German (@UJehle )
- [ ] release (@UJehle )

**Comment by UJehle** [comment]
@EPajares I just had a look and made some edits. When you have time, you could also have a look at the texts and maybe make some final adjustments to the English version. Let me know when you think it's good, then I will translate it into German.
